//
// EstimateNetworkFee200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EstimateNetworkFee200Response: Sendable, Codable, Hashable {

    public var success: Bool?
    /** Same shape as POST /api/wallet/calculate-fee response (chain, networkFee, estimatedTime, currency, and chain-specific fields). */
    public var data: JSONValue?

    public init(success: Bool? = nil, data: JSONValue? = nil) {
        self.success = success
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

