//
// GetIntegrations200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetIntegrations200Response: Sendable, Codable, Hashable {

    public var integrations: [GetIntegrations200ResponseIntegrationsInner]?

    public init(integrations: [GetIntegrations200ResponseIntegrationsInner]? = nil) {
        self.integrations = integrations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case integrations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(integrations, forKey: .integrations)
    }
}

