//
// GetMultiRoleConfig200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetMultiRoleConfig200ResponseData: Sendable, Codable, Hashable {

    public var isEnabled: Bool?
    public var defaultRole: String?
    public var settings: JSONValue?
    public var roles: [JSONValue]?

    public init(isEnabled: Bool? = nil, defaultRole: String? = nil, settings: JSONValue? = nil, roles: [JSONValue]? = nil) {
        self.isEnabled = isEnabled
        self.defaultRole = defaultRole
        self.settings = settings
        self.roles = roles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isEnabled
        case defaultRole
        case settings
        case roles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isEnabled, forKey: .isEnabled)
        try container.encodeIfPresent(defaultRole, forKey: .defaultRole)
        try container.encodeIfPresent(settings, forKey: .settings)
        try container.encodeIfPresent(roles, forKey: .roles)
    }
}

