//
// GetOrganizationMembers200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetOrganizationMembers200Response: Sendable, Codable, Hashable {

    public var members: [User]?
    public var total: Int?

    public init(members: [User]? = nil, total: Int? = nil) {
        self.members = members
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case members
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(members, forKey: .members)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

