//
// GetPendingPayouts200ResponseDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetPendingPayouts200ResponseDataInner: Sendable, Codable, Hashable {

    public var id: String?
    public var project: String?
    public var currency: String?
    public var grossAmount: Double?
    public var netAmount: Double?
    public var toAddress: String?
    public var txHash: String?
    public var status: String?
    public var error: String?
    public var retryCount: Int?
    public var scheduledAt: Date?
    public var processedAt: Date?
    public var createdAt: Date?

    public init(id: String? = nil, project: String? = nil, currency: String? = nil, grossAmount: Double? = nil, netAmount: Double? = nil, toAddress: String? = nil, txHash: String? = nil, status: String? = nil, error: String? = nil, retryCount: Int? = nil, scheduledAt: Date? = nil, processedAt: Date? = nil, createdAt: Date? = nil) {
        self.id = id
        self.project = project
        self.currency = currency
        self.grossAmount = grossAmount
        self.netAmount = netAmount
        self.toAddress = toAddress
        self.txHash = txHash
        self.status = status
        self.error = error
        self.retryCount = retryCount
        self.scheduledAt = scheduledAt
        self.processedAt = processedAt
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case project
        case currency
        case grossAmount
        case netAmount
        case toAddress
        case txHash
        case status
        case error
        case retryCount
        case scheduledAt
        case processedAt
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(project, forKey: .project)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(grossAmount, forKey: .grossAmount)
        try container.encodeIfPresent(netAmount, forKey: .netAmount)
        try container.encodeIfPresent(toAddress, forKey: .toAddress)
        try container.encodeIfPresent(txHash, forKey: .txHash)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encodeIfPresent(retryCount, forKey: .retryCount)
        try container.encodeIfPresent(scheduledAt, forKey: .scheduledAt)
        try container.encodeIfPresent(processedAt, forKey: .processedAt)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}

