//
// ListRoles200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ListRoles200Response: Sendable, Codable, Hashable {

    public var roles: [JSONValue]?
    public var total: Int?

    public init(roles: [JSONValue]? = nil, total: Int? = nil) {
        self.roles = roles
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case roles
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(roles, forKey: .roles)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

