//
// Organization.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Organization: Sendable, Codable, Hashable {

    public enum DeploymentType: String, Sendable, Codable, CaseIterable {
        case shared = "shared"
        case dedicated = "dedicated"
    }
    public var id: String?
    public var name: String?
    public var slug: String?
    public var description: String?
    /** Optional logo URL. Org-related emails use the platform logo (env); this field is for legacy or future UI use only. */
    public var logo: String?
    public var website: String?
    public var plan: Plan?
    public var usage: Usage?
    public var limits: Limits?
    public var billing: Billing?
    /** May include customDomainAddon (optional billing/legacy flag; not required for custom domains on Growth/Scale). */
    public var settings: JSONValue?
    public var deploymentType: DeploymentType?
    /** Dedicated API/DB routing; may include edgeTlsStatus, infraMeteringLastReportAt. */
    public var dedicated: JSONValue?
    public var preferredRegion: String?
    public var infrastructureEnvironments: [JSONValue]?
    public var allowedDomains: [JSONValue]?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: String? = nil, name: String? = nil, slug: String? = nil, description: String? = nil, logo: String? = nil, website: String? = nil, plan: Plan? = nil, usage: Usage? = nil, limits: Limits? = nil, billing: Billing? = nil, settings: JSONValue? = nil, deploymentType: DeploymentType? = nil, dedicated: JSONValue? = nil, preferredRegion: String? = nil, infrastructureEnvironments: [JSONValue]? = nil, allowedDomains: [JSONValue]? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.name = name
        self.slug = slug
        self.description = description
        self.logo = logo
        self.website = website
        self.plan = plan
        self.usage = usage
        self.limits = limits
        self.billing = billing
        self.settings = settings
        self.deploymentType = deploymentType
        self.dedicated = dedicated
        self.preferredRegion = preferredRegion
        self.infrastructureEnvironments = infrastructureEnvironments
        self.allowedDomains = allowedDomains
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case name
        case slug
        case description
        case logo
        case website
        case plan
        case usage
        case limits
        case billing
        case settings
        case deploymentType
        case dedicated
        case preferredRegion
        case infrastructureEnvironments
        case allowedDomains
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(logo, forKey: .logo)
        try container.encodeIfPresent(website, forKey: .website)
        try container.encodeIfPresent(plan, forKey: .plan)
        try container.encodeIfPresent(usage, forKey: .usage)
        try container.encodeIfPresent(limits, forKey: .limits)
        try container.encodeIfPresent(billing, forKey: .billing)
        try container.encodeIfPresent(settings, forKey: .settings)
        try container.encodeIfPresent(deploymentType, forKey: .deploymentType)
        try container.encodeIfPresent(dedicated, forKey: .dedicated)
        try container.encodeIfPresent(preferredRegion, forKey: .preferredRegion)
        try container.encodeIfPresent(infrastructureEnvironments, forKey: .infrastructureEnvironments)
        try container.encodeIfPresent(allowedDomains, forKey: .allowedDomains)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}

