//
// PatchProjectFcmConfigRequestOneOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PatchProjectFcmConfigRequestOneOf: Sendable, Codable, Hashable {

    /** Firebase service account JSON (client_email, private_key, etc.) */
    public var serviceAccountJson: JSONValue

    public init(serviceAccountJson: JSONValue) {
        self.serviceAccountJson = serviceAccountJson
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case serviceAccountJson
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(serviceAccountJson, forKey: .serviceAccountJson)
    }
}

