//
// UpdateMultiRoleSettings200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateMultiRoleSettings200Response: Sendable, Codable, Hashable {

    public var success: Bool?
    public var message: String?
    /** Same shape as GET `/multi-role` — `isEnabled`, `defaultRole`, `settings`, and `roles` (no raw MultiRoleFeature document). */
    public var data: JSONValue?

    public init(success: Bool? = nil, message: String? = nil, data: JSONValue? = nil) {
        self.success = success
        self.message = message
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case message
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

