/*
MUDBASESDK

Testing BugAnalysisAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mudbase

import (
	"context"
	. "github.com/mudbase/mudbase-go-sdk"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_mudbase_BugAnalysisAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test BugAnalysisAPIService StartBugAnalysisScan", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.BugAnalysisAPI.StartBugAnalysisScan(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BugAnalysisAPIService StartBugAnalysisScanByProject", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var projectId string

		httpRes, err := apiClient.BugAnalysisAPI.StartBugAnalysisScanByProject(context.Background(), projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
