//
// RoleElevationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class RoleElevationAPI {

    /**
     Approve/reject role elevation request (admin only)
     
     - parameter orgId: (path)  
     - parameter requestId: (path)  
     - parameter approveRoleElevationRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ApproveRoleElevation200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func approveRoleElevation(orgId: String, requestId: String, approveRoleElevationRequest: ApproveRoleElevationRequest, apiConfiguration: MudbaseSDKAPIConfiguration = MudbaseSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ApproveRoleElevation200Response {
        return try await approveRoleElevationWithRequestBuilder(orgId: orgId, requestId: requestId, approveRoleElevationRequest: approveRoleElevationRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Approve/reject role elevation request (admin only)
     - POST /api/orgs/{orgId}/role-elevation/{requestId}/approve
     - Admin approves or rejects a role elevation request
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter orgId: (path)  
     - parameter requestId: (path)  
     - parameter approveRoleElevationRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ApproveRoleElevation200Response> 
     */
    open class func approveRoleElevationWithRequestBuilder(orgId: String, requestId: String, approveRoleElevationRequest: ApproveRoleElevationRequest, apiConfiguration: MudbaseSDKAPIConfiguration = MudbaseSDKAPIConfiguration.shared) -> RequestBuilder<ApproveRoleElevation200Response> {
        var localVariablePath = "/api/orgs/{orgId}/role-elevation/{requestId}/approve"
        let orgIdPreEscape = "\(APIHelper.mapValueToPathItem(orgId))"
        let orgIdPostEscape = orgIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{orgId}", with: orgIdPostEscape, options: .literal, range: nil)
        let requestIdPreEscape = "\(APIHelper.mapValueToPathItem(requestId))"
        let requestIdPostEscape = requestIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{requestId}", with: requestIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: approveRoleElevationRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApproveRoleElevation200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter status
     */
    public enum Status_getPendingRoleElevationRequests: String, Sendable, CaseIterable {
        case pending = "pending"
        case approved = "approved"
        case rejected = "rejected"
    }

    /**
     Get pending role elevation requests (admin only)
     
     - parameter orgId: (path)  
     - parameter status: (query)  (optional, default to .pending)
     - parameter page: (query)  (optional, default to 1)
     - parameter limit: (query)  (optional, default to 50)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetPendingRoleElevationRequests200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getPendingRoleElevationRequests(orgId: String, status: Status_getPendingRoleElevationRequests? = nil, page: Int? = nil, limit: Int? = nil, apiConfiguration: MudbaseSDKAPIConfiguration = MudbaseSDKAPIConfiguration.shared) async throws(ErrorResponse) -> GetPendingRoleElevationRequests200Response {
        return try await getPendingRoleElevationRequestsWithRequestBuilder(orgId: orgId, status: status, page: page, limit: limit, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get pending role elevation requests (admin only)
     - GET /api/orgs/{orgId}/role-elevation/pending
     - Get all pending role elevation requests requiring admin approval
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter orgId: (path)  
     - parameter status: (query)  (optional, default to .pending)
     - parameter page: (query)  (optional, default to 1)
     - parameter limit: (query)  (optional, default to 50)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetPendingRoleElevationRequests200Response> 
     */
    open class func getPendingRoleElevationRequestsWithRequestBuilder(orgId: String, status: Status_getPendingRoleElevationRequests? = nil, page: Int? = nil, limit: Int? = nil, apiConfiguration: MudbaseSDKAPIConfiguration = MudbaseSDKAPIConfiguration.shared) -> RequestBuilder<GetPendingRoleElevationRequests200Response> {
        var localVariablePath = "/api/orgs/{orgId}/role-elevation/pending"
        let orgIdPreEscape = "\(APIHelper.mapValueToPathItem(orgId))"
        let orgIdPostEscape = orgIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{orgId}", with: orgIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "status": (wrappedValue: status?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetPendingRoleElevationRequests200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get role elevation status
     
     - parameter projectId: (path)  
     - parameter roleSlug: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetRoleElevationStatus200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRoleElevationStatus(projectId: String, roleSlug: String? = nil, apiConfiguration: MudbaseSDKAPIConfiguration = MudbaseSDKAPIConfiguration.shared) async throws(ErrorResponse) -> GetRoleElevationStatus200Response {
        return try await getRoleElevationStatusWithRequestBuilder(projectId: projectId, roleSlug: roleSlug, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get role elevation status
     - GET /api/projects/{projectId}/role-elevation/status
     - Get status of pending role elevation requests for current user
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - parameter roleSlug: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetRoleElevationStatus200Response> 
     */
    open class func getRoleElevationStatusWithRequestBuilder(projectId: String, roleSlug: String? = nil, apiConfiguration: MudbaseSDKAPIConfiguration = MudbaseSDKAPIConfiguration.shared) -> RequestBuilder<GetRoleElevationStatus200Response> {
        var localVariablePath = "/api/projects/{projectId}/role-elevation/status"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "roleSlug": (wrappedValue: roleSlug?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetRoleElevationStatus200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Request role elevation
     
     - parameter projectId: (path)  
     - parameter requestRoleElevationRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestRoleElevation200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func requestRoleElevation(projectId: String, requestRoleElevationRequest: RequestRoleElevationRequest, apiConfiguration: MudbaseSDKAPIConfiguration = MudbaseSDKAPIConfiguration.shared) async throws(ErrorResponse) -> RequestRoleElevation200Response {
        return try await requestRoleElevationWithRequestBuilder(projectId: projectId, requestRoleElevationRequest: requestRoleElevationRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Request role elevation
     - POST /api/projects/{projectId}/role-elevation/request
     - User requests to upgrade to a specific role. May require payment, KYC, or admin approval based on role configuration.
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - parameter requestRoleElevationRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<RequestRoleElevation200Response> 
     */
    open class func requestRoleElevationWithRequestBuilder(projectId: String, requestRoleElevationRequest: RequestRoleElevationRequest, apiConfiguration: MudbaseSDKAPIConfiguration = MudbaseSDKAPIConfiguration.shared) -> RequestBuilder<RequestRoleElevation200Response> {
        var localVariablePath = "/api/projects/{projectId}/role-elevation/request"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestRoleElevationRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RequestRoleElevation200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Upload verification documents
     
     - parameter projectId: (path)  
     - parameter uploadVerificationDocumentsRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func uploadVerificationDocuments(projectId: String, uploadVerificationDocumentsRequest: UploadVerificationDocumentsRequest, apiConfiguration: MudbaseSDKAPIConfiguration = MudbaseSDKAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await uploadVerificationDocumentsWithRequestBuilder(projectId: projectId, uploadVerificationDocumentsRequest: uploadVerificationDocumentsRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Upload verification documents
     - POST /api/projects/{projectId}/role-elevation/documents
     - Upload KYC/verification documents for role elevation
     - Bearer Token:
       - type: http
       - name: OrgBearerAuth
     - Bearer Token:
       - type: http
       - name: ProjectBearerAuth
     - parameter projectId: (path)  
     - parameter uploadVerificationDocumentsRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func uploadVerificationDocumentsWithRequestBuilder(projectId: String, uploadVerificationDocumentsRequest: UploadVerificationDocumentsRequest, apiConfiguration: MudbaseSDKAPIConfiguration = MudbaseSDKAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/projects/{projectId}/role-elevation/documents"
        let projectIdPreEscape = "\(APIHelper.mapValueToPathItem(projectId))"
        let projectIdPostEscape = projectIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{projectId}", with: projectIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: uploadVerificationDocumentsRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
